language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip3 install future
  - pip install .
# command to run tests
script:
  - pytest tests/test.py
  
after_success:
  - cat tests/pikachu_testpass.txt
